### ISSUE TITLE
Crash at method imageAspectScaledToFillSize

### ISSUE THREAD

**Issue by ppamorim** [Alamofire/AlamofireImage#54] opened 2015-11-25 17:06 UTC
Hi Alamofire team, I've tested my app on a iPhone 4S, 5, 5S and works fine. But when I test on a 6 or 6S, this happens:

    unexpectedly found nil while unwrapping an Optional value

![captura de tela 2015-11-25 as 14 36 24](https://cloud.githubusercontent.com/assets/5521682/11403243/faf0891a-9382-11e5-8865-f1cbdec94e9b.png)

I'm using the filter to create the rounded borders at the image, I`m using the version 2.1.1 and Swift 2.0.
```swift
var filter : ImageFilter? = nil

    ...

func tableView(tableView: UITableView, cellForRowAtIndexPath indexPath: NSIndexPath) -> UITableViewCell {
    let cell = tableView.dequeueReusableCellWithIdentifier("Cell", forIndexPath: indexPath) as! Cell
    let object = (self.objects?.objectAtIndex(indexPath.row))! as! Object
    
    cell.title.text = object.title

    if self.filter == nil {
      self.filter = AspectScaledToFillSizeWithRoundedCornersFilter(
      size: cell.image.frame.size, radius: 5.0)
    }
   ImageHelper.loadImage(cell.image, object: object, filter: filter, .None)
   return cell
}
```

The method to load the image is:

```swift
class func loadImage(imageView: UIImageView, object : Object, filter: ImageFilter?, imageTransition: UIImageView.ImageTransition) {
    
    let stringUrl = createURLImage(object)

    if let url = NSURL(string: stringUrl) {
      imageView.af_setImageWithURL(
        url,
        placeholderImage: UIImage(named: "app_logo"),
        filter: filter,
        imageTransition: imageTransition)
    }
}
```
Is it a bug? If I comment the code, it works fine.

**Comment by ppamorim** [comment] 2015-12-01 12:36
I will create a sample app to prove it.

**Comment by cnoon** [comment] 2015-12-10 03:42
Thanks for submitting this issue @ppamorim. Unfortunately, I can't reproduce this issue. The iOS Example app in AlamofireImage actually uses the `AspectScaledToFillSizeWithRoundedCornersFilter` for all the collection view cells. I just ran the example app on my iPhone 6S without any issues.

I'm going to close this issue out. If you can create a sample project or explain to me how to reproduce the issue in any way, then I'll be happy to re-open this issue and continue to investigate.

Cheers. 🍻

**Closed by cnoon** 2015-12-10 03:42 UTC

**Comment by ppamorim** [comment] 2015-12-14 16:25
Created!

https://github.com/ppamorim/Fun-with-Swift/blob/master/Fun%20With%20Swift/AlamofireImageFilterController.swift

The bug happens on a iPhone 6 or newer.

**Comment by cnoon** [comment] 2015-12-16 08:23
Hi @ppamorim...what does `print(cell.someImage.frame.size)` report in your `cellForRowAtIndexPath` method? If it's reporting `CGSizeZero` then that's certainly the problem. If not, could you post the actual info?

**Comment by ppamorim** [comment] 2015-12-16 17:06
Second the log:

```Swift
<UIImageView: 0x7f998ac5eab0; frame = (0 0; 0 0); userInteractionEnabled = NO; layer = <CALayer: 0x7f998ac753b0>>
```
The frame of the cell is created at the updateConstraints() method. I need to do this because I use the `AutoLayout` to create the constraints for the view.

**Comment by cnoon** [comment] 2015-12-17 03:41
Yep, that's the problem. You cannot provide a size of `zero` and expect an image to be created. You'll need to provide the correct size to the filter for this to work correctly.

**Comment by ppamorim** [comment] 2015-12-17 13:55
Why I need to inform the frame of the view. AlamofireImage loader cannot do it ifself?

**Comment by cnoon** [comment] 2015-12-18 16:29
AlamofireImage cannot magically infer what the size of an image should be without you telling it. Your code currently tells AlamofireImage to make an image with size (0, 0). That is not supported and will result in the error you are currently seeing. Once you pass it a valid size, everything will start working properly.

**Comment by ppamorim** [comment] 2016-01-11 04:08
Do you would find a solution for this problem? I don't know if it's a problem with PureLayout(just a wrapper around AutoLayout) or with this library.
I don't know why this library needs the current size of the view. I think this library can do any filter process after the request of image.
Another question: Do you have tested my sample project? I'll glad if you help me. I don't mind any solution. :(

**Comment by santensuru** [comment] 2017-06-02 13:51
Hi, i have same problem
but in my case, the image found nil when i scroll the uicollectionview of image (af_setimage) to fast
N.B: before using af_setimage, i create my framework and run it in background process -> and get af_setimage inside main thread block
can you help me?
thx

my code:

let backgroundQueue = DispatchQueue(label: "background",
                                            qos: .background,
                                            target: nil)
        backgroundQueue.async {
            self.contentMode = .scaleAspectFit // placeholder
            
            let placeholderImage = UIImage(named: "placeholder-standar-white")!
            placeholderImage.afInflate()
            
            let filter = AspectScaledToFillSizeFilter(
                size: self.frame.size
            )
            
            let imageTransition = UIImageView.ImageTransition.crossDissolve(0.2)
            
            DispatchQueue.main.async(execute: {
                self.af_setImage(
                    withURL: withURL,
                    placeholderImage: placeholderImage,
                    filter: filter,
                    imageTransition: imageTransition,
                    completion: { res in
                        self.contentMode = .scaleAspectFill // image
                        self.image?.afInflate()
                })
            })
        }

**Comment by santensuru** [comment] 2017-06-03 06:00
Oh, i.c
i just found the problem maker, it's cause my UIImageView frame is initiated via code
