### ISSUE TITLE
Feature request: Set image scale in ImageDownloader downloads

### ISSUE THREAD

**Issue by solidfox** [Alamofire/AlamofireImage#118] opened 2016-06-06 13:19 UTC
This should be a common desire as many would probably like to set image scale depending on the @2x/@3x part of the filename. Please correct me if this is already available.

**Comment by cnoon** [comment] 2016-08-22 03:45
This is not currently available by design. The `ImageDownloader` always sets the image scale to the `UIScreen` scale which will adjust the `size` accordingly. This is certainly the default behavior that most users would expect. Using the remote URL filename seems problematic and error prone.

If you need to modify this behavior, you can easily modify the image's scale using an `ImageFilter` if that's really what you "need" to do. But again, I question why you'd actually need to do this. Instead, you want to select the appropriate URL client side depending on your device's scale factor, then allow AFI to set the scale automatically for you.

I lean towards keeping the `imageScale` parameter out of the `ImageDownloader` APIs unless there's an extremely good reason for adding it.

I'm going to close this issue out for now. If you feel strongly here, please provide more info and I'd be happy to discuss further.

Cheers. 🍻

**Closed by cnoon** 2016-08-22 03:45 UTC
