### ISSUE TITLE
Running example code gives EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by kylebrowning** [Alamofire/AlamofireImage#229] opened 2017-01-05 00:04 UTC
```
        let url = URL(string: "https://httpbin.org/image/png")!
        
        imageView.af_setImage(withURL: url)

```

Ran this inside a viewDidLoad method. Also try a viewDidAppear.

Image of error. http://imgur.com/a/fhiMB

**Comment by cnoon** [comment] 2017-02-26 22:01
Hi @kylebrowning,

Our apologies for not getting back to you sooner. Could you post an actual example project here? It's very difficult to debug crash cases without a project. This is also the most common use case for AFI so I'm sure there's something pretty obviously wrong if we had the project to look at. 

Also, what version of Swift, Xcode and AlamofireImage were you using?

**Comment by kylebrowning** [comment] 2017-02-26 22:03
referring to the code here, https://github.com/Alamofire/AlamofireImage/tree/master/Example

**Comment by cnoon** [comment] 2017-02-26 23:25
Gotcha. I just ran the example project on Xcode 8.2.1 against AFI 3.2.0 on an iOS 10.2 simulator without any issues. Could you give me some more info to go on?

**Comment by cnoon** [comment] 2017-06-17 02:58
I cannot reproduce this behavior at all. I'm going to go ahead and close this out unless we find some additional information to go on.

**Closed by cnoon** 2017-06-17 02:58 UTC
Labels: needs feedback
