### ISSUE TITLE
CGDataProviderCopyData crash in production

### ISSUE THREAD

**Issue by alexge** [Alamofire/AlamofireImage#439] opened 2021-03-10 11:48 UTC
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

We use SPM to add AlamoFireImage as a dependency to download, cache, and show images across numerous collection views in the app. We are using the given `af.setImage(withURL....)` function on our UIImageViews. 

## What did you expect to happen?

Images to download and show as expected

## What happened instead?

Overall this works great. I've never seen an issue, but I have received 2 crash reports from Apple of the same crash on CGDataProviderCopyData. The first was on an iPhone 8 Plus and the second was on an iPhone SE, both running iOS 14.4. 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/826624/110624531-3b020e00-8196-11eb-8e5c-d8cc2e4b21be.png">

Looking at the stack trace, it seems to come from ImageResponseSerializer which is in the library, so I don't have much more information to go on. Any thoughts you might have to fixing this or ideas for further investigation would be greatly appreciated.

## Alamofire Environment

**Alamofire version:** 4.1
**Xcode version:** 12.4
**Swift version:** 5
**Platform(s) running AlamofireImage:** iOS 12-14
**macOS version running Xcode:** 10.15.6

**Comment by jshier** [comment] 2021-04-03 20:50
This is likely a duplicate of #332, caused by downloading images which are too large to inflate into memory. There's a workaround in that thread.

**Closed by jshier** 2021-04-03 20:50 UTC
